### ISSUE TITLE
error cased by lower case?

### ISSUE THREAD

**Issue by fishtez** [fishtez/blackjack#10]
![lower case](https://cloud.githubusercontent.com/assets/12114756/7488158/98e5f03c-f37a-11e4-9628-54101fbb82ca.png)

**Comment by DavidL47** [comment]
when i compile the updated one from github i don't get that

**Comment by DavidL47** [comment]
also lower case h still works

**Comment by fishtez** [comment]
sorry, my version wasn't syncing properly.
