### ISSUE TITLE
error check ace not always called

### ISSUE THREAD

**Issue by fishtez** [fishtez/blackjack#20]
![not always asking ace](https://cloud.githubusercontent.com/assets/12114756/7553215/d3c2d00e-f69e-11e4-9ddb-be950073c85b.png)

**Comment by DavidL47** [comment]
hey, i changed some code around to fix the problem with the dealer always
getting 28 and i think it fixed this issue somehow, i got an ace on the
first game and it asked me and on like the 4th one i got an ace and it
asked me if i wanted 1 or 11

**Comment by fishtez** [comment]
is this fixed now? i haven't tested for it.

**Comment by DavidL47** [comment]
Its fixed

**Comment by DavidL47** [comment]
never mind just retested it, it seems like it still can happen

**Comment by DavidL47** [comment]
okay now i fixed it  lol

**Comment by Zubz21** [comment]
Just wanted to make sure who is doing which flowchart. Marnie has already
completed Main.
So there is:
Wager
Play
Shuffle
Display
NewDeck
CheckAce
Card variables:

**Comment by DavidL47** [comment]
i already did shuffle display newdeck check ace and dealercheck ace

**Comment by DavidL47** [comment]
marnie has also already completed wager i believe

**Comment by DavidL47** [comment]
and the save/load one is finished

**Comment by fishtez** [comment]
I think the only one left to do is play. check the file on google drive,
though.

**Comment by fishtez** [comment]
Yea I did main, wager, save and load
