### ISSUE TITLE
error save doesnt load properly

### ISSUE THREAD

**Issue by fishtez** [fishtez/blackjack#22]
i uploaded the save and load save functions, it doesnt resume the save properly. the card names get jumbled. here is a screencap of the current issue:
![first reload attempt](https://cloud.githubusercontent.com/assets/12114756/7553436/ab04fd2c-f6ad-11e4-9ba1-691f438e1747.png)

**Comment by fishtez** [comment]
I think I figured it out. David, when you generate decks, your check(int y) function corresponds to multiples of 4, which works because when you generate the deck, you do it in chunks of 4 cards. When I try to re-populate the deck from the save file, my for loop isn't increasing in multiples of 4. Could you please take a look at it and see if you can think of how to adjust the function to properly format the names of loaded saves?

**Comment by DavidL47** [comment]
ill take a look at it today, i just finished the check functions for player
and dealer about to upload them and ill take a look at the save/load
function after i upload

**Comment by DavidL47** [comment]
the problem is with the .output function for display remaining i did a string = face + suitName in their so its combing the face and suitName a second time when u load ill try to see how i can change that so it will work

**Comment by DavidL47** [comment]
actually nevermind that doesnt seem like its the issue it saves the face by itself not with the suit

**Comment by DavidL47** [comment]
ok now i understand what its doing its taking each word for the face save , so when it sets face to whats ave its only taking "jack" and not the "of"

**Comment by DavidL47** [comment]
goin to change somethin that will fix it

**Comment by DavidL47** [comment]
Should work now

**Comment by Zubz21** [comment]
Visio wont download for me. Mighy end up using word unless they have it
downloaded at the lab

**Comment by fishtez** [comment]
I didn't see visio on the computer i was using on friday. I don't know if you can install things there.
