### ISSUE TITLE
need header comments for functions

### ISSUE THREAD

**Issue by fishtez** [fishtez/blackjack#23]
![function headers needed](https://cloud.githubusercontent.com/assets/12114756/7556975/ca593ace-f73b-11e4-8902-942ea6dfd5b9.png)

**Comment by DavidL47** [comment]
writing these now will be uploaded soon

**Comment by Zubz21** [comment]
Alrite i guess i will be doing play

**Comment by Zubz21** [comment]
So I have put all three into their won separate files however I get one
identifier that wont pass through under void new deck

deck[y].face = check(y); // this will set the face for four cards
deck[y + 1].face = check(y);
deck[y + 2].face = check(y);
deck[y + 3].face = check(y);

**Comment by fishtez** [comment]
could you please upload the files, so we can test it and see what you mean... or upload a screencap of the exact message it is giving you?
