### ISSUE TITLE
check identifier not found

### ISSUE THREAD

**Issue by fishtez** [fishtez/blackjack#26]
i'm still getting this error when i try to compile Card.cpp, Card.h and CardDriver.cpp

is it working for you guys?
![check identifier](https://cloud.githubusercontent.com/assets/12114756/7581114/b837752e-f833-11e4-83f4-a265384d656c.png)

**Comment by DavidL47** [comment]
getting same error

**Comment by DavidL47** [comment]
ok i got it running now

**Comment by DavidL47** [comment]
i moved the check y function to Card.cpp and declared it in card.h

**Comment by fishtez** [comment]
nice
