### ISSUE TITLE
error determining win/loss

### ISSUE THREAD

**Issue by fishtez** [fishtez/blackjack#4]
right now the cardNum variable is not the appropriate point value.

also, if this hand were actually dealt, both the dealer and the player are over 21, so it shouldn't be asking if they want to hit or stay, the hand is already over.

http://www.bicyclecards.com/card-games/rule/blackjack
"When all the players have placed their bets, the dealer gives one card face up to each player in rotation clockwise, and then one card face up to himself. Another round of cards is then dealt face up to each player, but the dealer takes his second card face down. Thus, each player except the dealer receives two cards face up, and the dealer receives one card face up and one card face down."

it should be dealing one card to the player, then one to the dealer, then another to the player. if the player is over 21 at that point, he has already lost and the play function should end.

![error uninitialized deck](https://cloud.githubusercontent.com/assets/12114756/7443700/808ccef6-f114-11e4-93f3-67d461a01e0e.png)

**Comment by DavidL47** [comment]
hmm when i ran it in the computer lab it would say you lose the moment u go
over 21 i must of copy and pasted it over badly or maybe its missing a part

**Comment by fishtez** [comment]
also old version
