### ISSUE TITLE
need to change point values

### ISSUE THREAD

**Issue by fishtez** [fishtez/blackjack#5]
the card numbers were set up to keep track of what card they were (ace, 3, jack, etc), they arent the appropriate values for keeping track of points. i suggest switching the card identifier to strings as the professor said in class, to keep track of the card type, and then associate point values to those strings. I've attached my notes from what the professor said was the easiest way to set up the basics of the program, but it doesnt need to be done that way. it just might be easier.

![csci notes](https://cloud.githubusercontent.com/assets/12114756/7443729/b8bcb4f6-f116-11e4-914a-f4b1195a141e.jpg)

**Comment by Zubz21** [comment]
Sorry guys i was in a movie. Im working on the class and the play right
now. Antthing u want to change?

**Comment by fishtez** [comment]
I think probably the most important thing right now is to make the class variables private and add the 'getter' and 'setter' member functions for the Card class. once that is done, it'll change the way play and shuffle are written.
second thing would be changing the card names to strings and setting the appropriate point values for them.

did you see my email about the project report/algorithms on google drive? i think we really need algorithms for play and shuffle before we go further.

**Comment by Zubz21** [comment]
Oh wow ok. I guess i have to rethink the classes then. So we are doing 2
classes. And i will look at the algorithms right now
