### ISSUE TITLE
error play stopped working

### ISSUE THREAD

**Issue by fishtez** [fishtez/blackjack#8]
i got this error while testing play. it just stopped here and didnt do anything or take input. it was while running the updatedMain that i just posted a few minutes ago.

![hanging on play](https://cloud.githubusercontent.com/assets/12114756/7486892/a09fe120-f361-11e4-86c4-bb5066870b9d.png)

**Comment by Zubz21** [comment]
Yes i got that same error. I dont know whats causing that

**Comment by fishtez** [comment]
it looks like a problem starting a new game. in case '4' of the main switch statement, it asks for the bet and then the play function should be called. maybe once you put play into a function, it'll be easier to see what the problem is

**Comment by fishtez** [comment]
old version
