### ISSUE TITLE
we have two main files!

### ISSUE THREAD

**Issue by fishtez** [fishtez/blackjack#9]
i just realized we have two main .cpp files now. blackMain.cpp and updatedMain.cpp.
they need to be merged, but i think zubeir and i have been editing updatedMain.cpp and david submitted stuff to blackMain.cpp. i don't want to delete anything because i'm not sure which is up to date. can you guys please look at your code put the most recent stuff into updatedMain.cpp.

after this is done i will delete blackMain.cpp

**Comment by DavidL47** [comment]
the code ive done to blackMain.cpp can only be tested once we have the
classes all done its functions that will use the private variables and if i
copy them to the updated one it will most likely mess it up so that it wont
compile so ill just copy them to another file for now.

**Comment by fishtez** [comment]
Zubeir have you done those functions yet? we need to get all of our code into one file ASAP so we can test things properly.

**Comment by DavidL47** [comment]
I dont think we made new deck into a function yet who was doing that?

**Comment by DavidL47** [comment]
i copied over everything i did on the blackmain.cpp so unless zubeir
changed anything on it i think its safe to delete it if u want to

**Comment by fishtez** [comment]
zubeir are you okay with me deleting blackMain.cpp?

**Comment by Zubz21** [comment]
its safe to delete

**Comment by Zubz21** [comment]
Ok here is the thing for the play function.It seems like I have to pass he
card objects through as an arguement because it i just reinitialize them
all in the function then every single card is a 14

**Comment by fishtez** [comment]
yeah, they need to be passed in. and if deck and hand are arrays, they may
need to be passed also

**Comment by Zubz21** [comment]
Yes they may be deleted. And i believe they are passed through reference
then cuz we manipulating them in the play function by setting them equal to
after use
